import type { GenerationResult } from '@/types';

export const mockGenerationResult = (overrides?: Partial<GenerationResult>): GenerationResult => ({
  parsedRequirement: {
    category: '冲锋衣',
    gender: '中性',
    ageRange: '25-35岁',
    scenes: ['徒步', '通勤'],
    season: '春秋',
    targetPrice: 899,
    orderQuantity: 500,
    functionPriorities: ['防水', '防风', '透湿'],
    stylePositioning: '专业户外',
    quickResponseRequired: true,
    constraints: ['成本控制在45%以内'],
  },
  fabricRecommendations: [
    {
      fabric: {
        id: 'f1',
        name: '高性能尼龙三层复合面料',
        category: '冲锋衣面料',
        composition: '尼龙',
        structure: '3L',
        weightGsm: 120,
        widthCm: 150,
        pricePerMeter: 68,
        hydrostaticHead: 20000,
        breathability: 15000,
        windproof: true,
        waterRepellent: 'DWR',
        elasticity: '微弹',
        abrasionResistance: '高',
        suitableScenes: ['徒步', '通勤'],
        suitableProducts: ['冲锋衣'],
        suitableSeasons: ['春秋'],
        moqMeters: 1000,
        stockStatus: '现货',
        supplier: '某面料厂',
        riskNotes: '需注意交期',
      },
      totalScore: 88,
      sceneScore: 90,
      functionScore: 85,
      priceScore: 80,
      quickResponseScore: 95,
      seasonScore: 85,
      recommendationReason: '综合性能优秀',
    },
  ],
  selectedStyle: {
    id: 's1',
    name: '经典硬壳冲锋衣',
    category: '冲锋衣',
    gender: '中性',
    scenes: ['徒步', '通勤'],
    season: '春秋',
    silhouette: '标准',
    length: '常规',
    hood: '可拆卸头盔兼容帽',
    closure: '防水拉链',
    pockets: '胸前口袋+插手袋',
    cuff: '魔术贴调节袖口',
    hem: '下摆抽绳',
    ventilation: '腋下透气拉链',
    process: '全压胶工艺',
    costLevel: '中高',
    productionDifficulty: '中',
    riskNotes: '压胶工艺要求高',
    designReason: '适合专业户外场景',
    colorSuggestions: ['藏青', '黑色'],
    suitablePriceRange: { min: 600, max: 1200 },
  },
  costResult: {
    bomItems: [
      { name: '面料', usage: '1.8米', unitPrice: 68, subtotal: 122.4, note: '主面料' },
      { name: '拉链', usage: '5条', unitPrice: 8, subtotal: 40, note: 'YKK' },
    ],
    baseCost: 180,
    lossCost: 18,
    samplePatternAmortization: 12,
    estimatedUnitCost: 210,
    costRangeLow: 178.5,
    costRangeHigh: 241.5,
    retailPrice: 899,
    costRate: 23.4,
    costWarnings: ['成本率偏低需复核'],
    laborMultiplier: 1.2,
    laborMultiplierNote: '中等复杂度',
  },
  marketingCopy: {
    title: '专业级三合一冲锋衣',
    sellingPoints: ['防水透气', '轻量化设计', '多场景适用'],
    tiktokScript: '这款冲锋衣防水透气，户外必备',
    detailPageCopy: '详情页文案内容',
    liveScript: '直播间话术内容',
  },
  riskWarnings: [
    { category: '成本', severity: '中', message: '建议复核面料成本' },
  ],
  summary: '这是一款面向专业户外人群的冲锋衣方案',
  ...overrides,
});
